# ASDA Week 1 Homework

In [2]:
#1

In [3]:
#importing necessary libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings(action='ignore')

In [5]:
#setting max columns as none

In [6]:
pd.set_option('display.max_columns', None)

In [7]:
#reading the dataset

In [8]:
df=pd.read_csv("../additional_material/Sleep_health_and_lifestyle_dataset.csv")
df.head(5)

Person ID Gender  Age            Occupation  Sleep Duration  \
0          1   Male   27     Software Engineer             6.1   
1          2   Male   28                Doctor             6.2   
2          3   Male   28                Doctor             6.2   
3          4   Male   28  Sales Representative             5.9   
4          5   Male   28  Sales Representative             5.9   

   Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0                 6                       42             6   Overweight   
1                 6                       60             8       Normal   
2                 6                       60             8       Normal   
3                 4                       30             8        Obese   
4                 4                       30             8        Obese   

  Blood Pressure  Heart Rate  Daily Steps Sleep Disorder  
0         126/83          77         4200            NaN  
1         125/80          75        10000            NaN  
2         125/80          75        10000            NaN  
3         140/90          85         3000    Sleep Apnea  
4         140/90          85         3000    Sleep Apnea

In [9]:
#checking the shape of data

In [10]:
df.shape

(374, 13)

In [11]:
#no of rows

In [12]:
print("no of rows are:", df.shape[0])

no of rows are: 374


In [13]:
#no of columns

In [14]:
print("no of columns are:",df.shape[1])

no of columns are: 13


In [15]:
#2

In [16]:
#checking the datatypes of data

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Person ID                374 non-null    int64  
 1   Gender                   374 non-null    object 
 2   Age                      374 non-null    int64  
 3   Occupation               374 non-null    object 
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64  
 6   Physical Activity Level  374 non-null    int64  
 7   Stress Level             374 non-null    int64  
 8   BMI Category             374 non-null    object 
 9   Blood Pressure           374 non-null    object 
 10  Heart Rate               374 non-null    int64  
 11  Daily Steps              374 non-null    int64  
 12  Sleep Disorder           155 non-null    object 
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB


In [18]:
#checking the null values in the dataset

In [19]:
df.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [20]:
#unique values and count of unique values of each column

In [21]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [22]:
df['Gender'].nunique()

2

In [23]:
df['Person ID'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [24]:
df['Person ID'].nunique()

374

In [25]:
df['Age'].unique()

array([27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [26]:
df['Age'].nunique()

31

In [27]:
df['Occupation'].unique()

array(['Software Engineer', 'Doctor', 'Sales Representative', 'Teacher',
       'Nurse', 'Engineer', 'Accountant', 'Scientist', 'Lawyer',
       'Salesperson', 'Manager'], dtype=object)

In [28]:
df['Occupation'].nunique()

11

In [29]:
df['Sleep Duration'].unique()

array([6.1, 6.2, 5.9, 6.3, 7.8, 6. , 6.5, 7.6, 7.7, 7.9, 6.4, 7.5, 7.2,
       5.8, 6.7, 7.3, 7.4, 7.1, 6.6, 6.9, 8. , 6.8, 8.1, 8.3, 8.5, 8.4,
       8.2])

In [30]:
df['Sleep Duration'].nunique()

27

In [31]:
df['Quality of Sleep'].unique()

array([6, 4, 7, 5, 8, 9])

In [32]:
df['Quality of Sleep'].nunique()

6

In [33]:
df['Physical Activity Level'].unique()

array([42, 60, 30, 40, 75, 35, 45, 50, 32, 70, 80, 55, 90, 47, 65, 85])

In [34]:
df['Physical Activity Level'].nunique()

16

In [35]:
df['Stress Level'].unique()

array([6, 8, 7, 4, 3, 5])

In [36]:
df['Stress Level'].nunique()

6

In [37]:
df['BMI Category'].unique()

array(['Overweight', 'Normal', 'Obese', 'Normal Weight'], dtype=object)

In [38]:
df['BMI Category'].nunique()

4

In [39]:
df['Blood Pressure'].unique()

array(['126/83', '125/80', '140/90', '120/80', '132/87', '130/86',
       '117/76', '118/76', '128/85', '131/86', '128/84', '115/75',
       '135/88', '129/84', '130/85', '115/78', '119/77', '121/79',
       '125/82', '135/90', '122/80', '142/92', '140/95', '139/91',
       '118/75'], dtype=object)

In [40]:
df['Blood Pressure'].nunique()

25

In [41]:
df['Heart Rate'].unique()

array([77, 75, 85, 82, 70, 80, 78, 69, 72, 68, 76, 81, 65, 84, 74, 67, 73,
       83, 86])

In [42]:
df['Heart Rate'].nunique()

19

In [43]:
df['Daily Steps'].unique()

array([ 4200, 10000,  3000,  3500,  8000,  4000,  4100,  6800,  5000,
        7000,  5500,  5200,  5600,  3300,  4800,  7500,  7300,  6200,
        6000,  3700])

In [44]:
df['Daily Steps'].nunique()

20

In [45]:
df['Sleep Disorder'].unique()

array([nan, 'Sleep Apnea', 'Insomnia'], dtype=object)

In [46]:
df['Sleep Disorder'].nunique()

2

In [47]:
#3

In [48]:
#checking descriptive statistics of data

In [49]:
df.describe()

Person ID         Age  Sleep Duration  Quality of Sleep  \
count  374.000000  374.000000      374.000000        374.000000   
mean   187.500000   42.184492        7.132086          7.312834   
std    108.108742    8.673133        0.795657          1.196956   
min      1.000000   27.000000        5.800000          4.000000   
25%     94.250000   35.250000        6.400000          6.000000   
50%    187.500000   43.000000        7.200000          7.000000   
75%    280.750000   50.000000        7.800000          8.000000   
max    374.000000   59.000000        8.500000          9.000000   

       Physical Activity Level  Stress Level  Heart Rate   Daily Steps  
count               374.000000    374.000000  374.000000    374.000000  
mean                 59.171123      5.385027   70.165775   6816.844920  
std                  20.830804      1.774526    4.135676   1617.915679  
min                  30.000000      3.000000   65.000000   3000.000000  
25%                  45.000000      4.000000   68.000000   5600.000000  
50%                  60.000000      5.000000   70.000000   7000.000000  
75%                  75.000000      7.000000   72.000000   8000.000000  
max                  90.000000      8.000000   86.000000  10000.000000

In [50]:
#including all the categorical columns in dataset

In [51]:
df.select_dtypes(exclude=np.number)

Gender            Occupation BMI Category Blood Pressure Sleep Disorder
0      Male     Software Engineer   Overweight         126/83            NaN
1      Male                Doctor       Normal         125/80            NaN
2      Male                Doctor       Normal         125/80            NaN
3      Male  Sales Representative        Obese         140/90    Sleep Apnea
4      Male  Sales Representative        Obese         140/90    Sleep Apnea
..      ...                   ...          ...            ...            ...
369  Female                 Nurse   Overweight         140/95    Sleep Apnea
370  Female                 Nurse   Overweight         140/95    Sleep Apnea
371  Female                 Nurse   Overweight         140/95    Sleep Apnea
372  Female                 Nurse   Overweight         140/95    Sleep Apnea
373  Female                 Nurse   Overweight         140/95    Sleep Apnea

[374 rows x 5 columns]

In [52]:
#checking most frequent value of each column 

In [53]:
df.select_dtypes(exclude=np.number).mode()

Gender Occupation BMI Category Blood Pressure Sleep Disorder
0   Male      Nurse       Normal         130/85    Sleep Apnea

In [54]:
df['Gender'].value_counts().head(1)[0]

np.int64(189)

In [55]:
df['Occupation'].value_counts().head(1)[0]

np.int64(73)

In [56]:
df['BMI Category'].value_counts().head(1)[0]

np.int64(195)

In [57]:
df['Blood Pressure'].value_counts().head(1)[0]

np.int64(99)

In [58]:
df['Sleep Disorder'].value_counts().head(1)[0]

np.int64(78)

In [59]:
#checking frequency of most frequent value of the column

In [60]:
df['Gender'].value_counts(ascending=True).head(1)

Gender
Female    185
Name: count, dtype: int64

In [61]:
df['Occupation'].value_counts(ascending=True).head(1)

Occupation
Manager    1
Name: count, dtype: int64

In [62]:
df['BMI Category'].value_counts(ascending=True).head(1)

BMI Category
Obese    10
Name: count, dtype: int64

In [63]:
df['Blood Pressure'].value_counts(ascending=True).head(1)

Blood Pressure
122/80    1
Name: count, dtype: int64

In [64]:
df['Sleep Disorder'].value_counts(ascending=True).head(1)

Sleep Disorder
Insomnia    77
Name: count, dtype: int64

In [65]:
#checking missing values in dataset

In [66]:
df.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [67]:
#percentage of missing values

In [68]:
df.isna().sum()/len(df)*100

Person ID                   0.00000
Gender                      0.00000
Age                         0.00000
Occupation                  0.00000
Sleep Duration              0.00000
Quality of Sleep            0.00000
Physical Activity Level     0.00000
Stress Level                0.00000
BMI Category                0.00000
Blood Pressure              0.00000
Heart Rate                  0.00000
Daily Steps                 0.00000
Sleep Disorder             58.55615
dtype: float64

In [69]:
#checking duplicate rows

In [70]:
df[df.duplicated()]

Empty DataFrame
Columns: [Person ID, Gender, Age, Occupation, Sleep Duration, Quality of Sleep, Physical Activity Level, Stress Level, BMI Category, Blood Pressure, Heart Rate, Daily Steps, Sleep Disorder]
Index: []

In [71]:
#checking percentage of duplicate rows

In [72]:
df.duplicated().sum()/len(df)*100

np.float64(0.0)

In [73]:
#4

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Person ID                374 non-null    int64  
 1   Gender                   374 non-null    object 
 2   Age                      374 non-null    int64  
 3   Occupation               374 non-null    object 
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64  
 6   Physical Activity Level  374 non-null    int64  
 7   Stress Level             374 non-null    int64  
 8   BMI Category             374 non-null    object 
 9   Blood Pressure           374 non-null    object 
 10  Heart Rate               374 non-null    int64  
 11  Daily Steps              374 non-null    int64  
 12  Sleep Disorder           155 non-null    object 
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB


In [75]:
#Does the dataset contain unnecessary columns? Which?

Yes the dataset contains unncessary column which is person id, This column is a unique identifier with all unique values. It should be dropped (or set as the index) before the main analysis.

In [76]:
#Do the data types correspond to the columns?

Yes, all the dataypes of columns correspond to the column. No typecasting is needed in here.

In [77]:
#Is the labelling of the columns appropriate?

Yes, the labelling of all the columns is appropriate

In [78]:
#Are there mixed values in column (e.g.,number and characters)?

No, there are no mixed values in the column

In [79]:
#Are string column clean?

Yes, the columns are clean. they do not contain any null values.

In [80]:
#Does the dataset look machine generated?

NA

In [81]:
#Other

NA

In [82]:
#5. Overall assessment
#Is it worth it to further analyze the dataset?